2024/03/05 11:24:08 [crit] 299566#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET /ws HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47:8080"
2024/03/05 11:24:08 [crit] 299566#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET /ws HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47:8080"
2024/03/05 11:24:13 [crit] 299566#0: *4 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET /ws HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47:8080"
2024/03/05 11:24:13 [crit] 299566#0: *4 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET /ws HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47:8080"
2024/03/05 11:24:22 [crit] 299566#0: *7 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET /ws HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47:8080"
2024/03/05 11:24:22 [crit] 299566#0: *7 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET /ws HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47:8080"
2024/03/05 11:44:54 [crit] 300151#0: *2 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:44:54 [crit] 300151#0: *2 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:44:54 [crit] 300151#0: *2 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:44:54 [crit] 300151#0: *2 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:45:00 [crit] 300151#0: *7 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:00 [crit] 300151#0: *7 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:03 [crit] 300151#0: *7 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:03 [crit] 300151#0: *7 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:04 [crit] 300151#0: *7 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:04 [crit] 300151#0: *7 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:21 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:21 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:21 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:45:21 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:45:22 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:22 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:22 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:45:22 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:45:23 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:23 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:23 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:45:23 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:45:24 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:24 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:24 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:45:24 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:45:47 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:47 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:47 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:47 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:48 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:45:48 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:46:21 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:46:21 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:46:22 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:46:22 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:46:22 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:46:22 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:46:23 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:46:23 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:46:23 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:46:23 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:47:18 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:47:18 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:47:18 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:47:18 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:47:18 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:47:18 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:48:15 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:48:15 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:48:15 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:48:15 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:48:15 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:48:15 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:48:15 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:48:15 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:48:16 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:48:16 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:48:16 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:48:16 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:32 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:32 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:32 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:32 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:47 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:47 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:48 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:48 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:45 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:45 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:53:25 [crit] 301000#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:53:25 [crit] 301000#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:53:25 [crit] 301000#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:53:25 [crit] 301000#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:53:32 [crit] 301000#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:53:32 [crit] 301000#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:53:32 [crit] 301000#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:53:32 [crit] 301000#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:57:32 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:57:32 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:57:32 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:57:32 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:57:34 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:57:34 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:57:34 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:57:34 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:57:34 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:57:34 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:57:34 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:57:34 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:57:34 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:57:34 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:57:34 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:57:34 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 13:01:51 [crit] 301000#0: *28 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 13:01:51 [crit] 301000#0: *28 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 13:01:51 [crit] 301000#0: *28 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 13:01:51 [crit] 301000#0: *28 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 13:01:51 [crit] 301000#0: *28 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 13:01:51 [crit] 301000#0: *28 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
