2024/03/05 11:24:08 [crit] 299566#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET /ws HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47:8080"
2024/03/05 11:24:08 [crit] 299566#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET /ws HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47:8080"
2024/03/05 11:24:13 [crit] 299566#0: *4 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET /ws HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47:8080"
2024/03/05 11:24:13 [crit] 299566#0: *4 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET /ws HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47:8080"
2024/03/05 11:24:22 [crit] 299566#0: *7 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET /ws HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47:8080"
2024/03/05 11:24:22 [crit] 299566#0: *7 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET /ws HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47:8080"
2024/03/05 11:44:54 [crit] 300151#0: *2 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:44:54 [crit] 300151#0: *2 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:44:54 [crit] 300151#0: *2 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:44:54 [crit] 300151#0: *2 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:45:00 [crit] 300151#0: *7 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:00 [crit] 300151#0: *7 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:03 [crit] 300151#0: *7 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:03 [crit] 300151#0: *7 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:04 [crit] 300151#0: *7 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:04 [crit] 300151#0: *7 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:21 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:21 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:21 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:45:21 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:45:22 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:22 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:22 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:45:22 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:45:23 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:23 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:23 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:45:23 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:45:24 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:24 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:24 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:45:24 [crit] 300702#0: *14 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:45:47 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:47 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:47 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:47 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:45:48 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:45:48 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:46:21 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:46:21 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:46:22 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:46:22 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:46:22 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:46:22 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:46:23 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:46:23 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:46:23 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:46:23 [crit] 300715#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:47:18 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:47:18 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:47:18 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:47:18 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:47:18 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:47:18 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:48:15 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:48:15 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:48:15 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:48:15 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:48:15 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:48:15 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:48:15 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:48:15 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:48:16 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:48:16 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:48:16 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:48:16 [crit] 300715#0: *18 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:32 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:32 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:32 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:32 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:33 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:34 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:47 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:47 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:49:48 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:49:48 [crit] 300848#0: *37 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:44 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:51:45 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:51:45 [crit] 300848#0: *82 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:53:25 [crit] 301000#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:53:25 [crit] 301000#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:53:25 [crit] 301000#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:53:25 [crit] 301000#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:53:32 [crit] 301000#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:53:32 [crit] 301000#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:53:32 [crit] 301000#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:53:32 [crit] 301000#0: *1 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.55, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:57:32 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:57:32 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:57:32 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:57:32 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:57:34 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:57:34 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:57:34 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:57:34 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:57:34 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:57:34 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:57:34 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:57:34 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:57:34 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:57:34 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 11:57:34 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 11:57:34 [crit] 301000#0: *10 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.238.0.79, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 13:01:51 [crit] 301000#0: *28 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 13:01:51 [crit] 301000#0: *28 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 13:01:51 [crit] 301000#0: *28 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 13:01:51 [crit] 301000#0: *28 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47"
2024/03/05 13:01:51 [crit] 301000#0: *28 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/05 13:01:51 [crit] 301000#0: *28 connect() to unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 10.239.120.56, server: 10.239.183.47, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.47", referrer: "http://10.239.183.47/"
2024/03/20 11:23:08 [error] 467028#0: *14621 upstream prematurely closed connection while reading response header from upstream, client: 10.239.120.56, server: 10.239.183.54, request: "POST /test_P HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/20 11:23:10 [error] 467028#0: *14621 upstream prematurely closed connection while reading response header from upstream, client: 10.239.120.56, server: 10.239.183.54, request: "POST /test_P HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/20 11:23:15 [error] 467028#0: *14624 upstream prematurely closed connection while reading response header from upstream, client: 10.239.120.56, server: 10.239.183.54, request: "POST /test_P HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/20 11:23:17 [error] 467028#0: *14624 upstream prematurely closed connection while reading response header from upstream, client: 10.239.120.56, server: 10.239.183.54, request: "POST /test_P HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/20 11:23:22 [error] 467028#0: *14630 upstream prematurely closed connection while reading response header from upstream, client: 10.239.120.56, server: 10.239.183.54, request: "POST /test_P HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/20 11:23:24 [error] 467028#0: *14630 upstream prematurely closed connection while reading response header from upstream, client: 10.239.120.56, server: 10.239.183.54, request: "POST /test_P HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/20 11:23:38 [error] 467028#0: *14633 upstream prematurely closed connection while reading response header from upstream, client: 10.239.120.56, server: 10.239.183.54, request: "POST /test_P HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/20 11:23:40 [error] 467028#0: *14633 upstream prematurely closed connection while reading response header from upstream, client: 10.239.120.56, server: 10.239.183.54, request: "POST /test_P HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/20 11:25:32 [error] 467028#0: *14636 upstream prematurely closed connection while reading response header from upstream, client: 10.239.120.56, server: 10.239.183.54, request: "POST /test_P HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/20 11:25:34 [error] 467028#0: *14636 upstream prematurely closed connection while reading response header from upstream, client: 10.239.120.56, server: 10.239.183.54, request: "POST /test_P HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/20 12:51:53 [error] 467028#0: *14676 upstream prematurely closed connection while reading response header from upstream, client: 10.239.120.56, server: 10.239.183.54, request: "POST /test_P HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/20 12:51:55 [error] 467028#0: *14676 upstream prematurely closed connection while reading response header from upstream, client: 10.239.120.56, server: 10.239.183.54, request: "POST /test_P HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/27 10:13:19 [error] 467028#0: *32458 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/27 10:13:21 [error] 467028#0: *32458 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/27 10:14:46 [error] 467028#0: *32461 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/27 10:14:48 [error] 467028#0: *32461 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/27 10:19:10 [error] 467028#0: *32464 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/27 10:19:12 [error] 467028#0: *32464 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/28 09:36:12 [error] 5945#0: *35 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById?article_id=1201583113 HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/28 09:36:13 [error] 5945#0: *35 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById?article_id=1201583113 HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/28 09:36:18 [error] 5945#0: *35 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById?article_id=1201583113 HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/28 09:36:20 [error] 5945#0: *35 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById?article_id=1201583113 HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/28 09:36:33 [error] 5945#0: *35 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById?article_id=1201583113 HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/28 09:36:34 [error] 5945#0: *35 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById?article_id=1201583113 HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/28 09:36:55 [error] 112933#0: *42 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById?article_id=1201583113 HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/28 09:36:57 [error] 112933#0: *42 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById?article_id=1201583113 HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/28 09:37:00 [error] 112933#0: *42 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById?article_id=1201583113 HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/28 09:37:02 [error] 112933#0: *42 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById?article_id=1201583113 HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/28 09:37:04 [error] 112933#0: *42 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById?article_id=1201583113 HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/28 09:37:06 [error] 112933#0: *42 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById?article_id=1201583113 HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/28 09:37:09 [error] 112933#0: *42 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById?article_id=1201583113 HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/28 09:37:11 [error] 112933#0: *42 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById?article_id=1201583113 HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/28 09:37:25 [error] 112933#0: *55 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /test HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/28 09:37:27 [error] 112933#0: *55 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /test HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/28 09:37:33 [error] 112933#0: *55 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /test HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/28 09:37:35 [error] 112933#0: *55 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /test HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/28 09:39:15 [error] 112981#0: *1 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById?article_id=1201583113 HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/28 09:39:17 [error] 112981#0: *1 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById?article_id=1201583113 HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/28 09:39:31 [error] 112981#0: *1 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById?article_id=1201583113 HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/28 09:39:33 [error] 112981#0: *1 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById?article_id=1201583113 HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/28 09:40:49 [error] 112981#0: *6 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById?article_id=1201583113 HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/28 09:40:51 [error] 112981#0: *6 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /searchById?article_id=1201583113 HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082"
2024/03/28 09:41:04 [error] 112981#0: *9 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /test HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/28 09:41:06 [error] 112981#0: *9 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /test HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/28 09:42:14 [error] 112981#0: *12 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /test HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/28 09:42:16 [error] 112981#0: *12 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /test HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/28 09:43:50 [error] 112981#0: *15 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /test HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/28 09:43:52 [error] 112981#0: *15 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /test HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/28 09:44:12 [error] 112981#0: *15 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /test HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/28 09:44:14 [error] 112981#0: *15 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /test HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/28 09:44:23 [error] 112981#0: *15 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /test HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/28 09:44:25 [error] 112981#0: *15 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /test HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/28 09:47:44 [error] 112981#0: *24 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /test HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
2024/03/28 09:47:45 [error] 112981#0: *24 upstream prematurely closed connection while reading response header from upstream, client: 10.238.0.79, server: 10.239.183.54, request: "GET /test HTTP/1.1", upstream: "uwsgi://unix:/root/webserve/AI-Web/ai-web/DjangoVue/script/uwsgi.sock:", host: "10.239.183.54:8082", referrer: "http://10.239.183.54/"
